#!/usr/bin/bash

set -v

mkdir backups

mv ~/.bash_profile `pwd`/backups/
mv ~/.bashrc `pwd`/backups/
mv ~/.bash_extras `pwd`/backups/
mv ~/.bin `pwd`/backups/

ln -s `pwd`/bash_profile ~/.bash_profile
ln -s `pwd`/bashrc ~/.bashrc
ln -s `pwd`/bin/ ~/.bin
ln -s `pwd`/bash_extras/ ~/.bash_extras
